# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  create:
    branches: [ "v9.0.0" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Prep the source to build on your distro.
        run: ./prep-source-build.sh --no-binary-removal
      
      - name: Build the .NET SDK
        run: ./build.sh -sb --clean-while-building -- /p:PortableBuild=true

      - name: Unpack and test
        run: |
          mkdir -p $HOME/dotnet
          tar zxf $(ls artifacts/assets/Release/dotnet-sdk-10.0.100-*.tar.gz) -C $HOME/dotnet
          $HOME/dotnet/dotnet --version
          $HOME/dotnet/dotnet --info
          
          
